# Generated by Django 4.2 on 2023-04-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='originalImage',
            field=models.ImageField(max_length=254, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='pngImage',
            field=models.ImageField(max_length=254, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='webpImage',
            field=models.ImageField(max_length=254, upload_to='images/'),
        ),
    ]
