# Generated by Django 4.1.1 on 2022-09-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=254, null=True)),
                ('fees', models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
