# Generated by Django 3.2 on 2022-12-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
