# Generated by Django 4.1.3 on 2022-11-02 04:20

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('roll', models.IntegerField()),
                ('city', models.CharField(max_length=254)),
                ('marks', models.IntegerField()),
                ('pass_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('empnum', models.IntegerField()),
                ('city', models.CharField(max_length=254)),
                ('salary', models.IntegerField()),
                ('join_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
