# Generated by Django 3.2 on 2022-10-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=254, null=True)),
                ('age', models.PositiveIntegerField()),
                ('address', models.CharField(blank=True, default=None, max_length=254, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('section', models.CharField(blank=True, default=None, max_length=254, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
