# Generated by Django 3.2 on 2022-09-30 04:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20220929_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('empnum', models.IntegerField()),
                ('city', models.CharField(max_length=254)),
                ('salary', models.IntegerField()),
                ('join_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
