# Generated by Django 3.2 on 2023-06-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_eat_pizzas', 'Can eat pizzas'), ('can_get_pizzas', 'Can get pizzas')],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
            ],
            options={
                'permissions': [('can_deliver_pizzas', 'Can deliver pizzas')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.person',),
        ),
    ]
