# Generated by Django 3.2 on 2022-12-14 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('roll', models.IntegerField()),
                ('city', models.CharField(max_length=254)),
                ('marks', models.IntegerField()),
                ('pass_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
